apiVersion: v2
name: freight-platform
version: 0.1.0
description: AI-driven Freight Optimization Platform for eliminating deadhead miles through dynamic load coordination
type: application
appVersion: "1.0.0"

keywords:
  - logistics
  - freight
  - optimization
  - ai
  - machine-learning

home: https://freightoptimization.com
sources:
  - https://github.com/freight-optimization/platform

maintainers:
  - name: Platform Engineering Team
    email: engineering@freightoptimization.com

dependencies:
  - name: postgresql
    version: 12.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.11.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: mongodb
    version: 13.6.0
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: elasticsearch
    version: 19.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled
  - name: kafka
    version: 22.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
  - name: prometheus
    version: 19.6.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: 6.50.0
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled

annotations:
  artifacthub.io/license: MIT
  artifacthub.io/prerelease: "true"
  artifacthub.io/containsSecurityUpdates: "false"