apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: optimization-engine
  namespace: default
  labels:
    app: optimization-engine
    component: optimization
    part-of: freight-optimization
  annotations:
    description: "Horizontal Pod Autoscaler for the Optimization Engine that executes AI algorithms for network-wide freight optimization, identifies Smart Hubs, and generates relay plans"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: optimization-engine
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Pods
    pods:
      metric:
        name: job_queue_length
      target:
        type: AverageValue
        averageValue: "5"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
      - type: Percent
        value: 30
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 180
      - type: Percent
        value: 10
        periodSeconds: 180
      selectPolicy: Min