apiVersion: v1
kind: Service
metadata:
  name: optimization-engine
  namespace: default
  labels:
    app: optimization-engine
    component: optimization
    part-of: freight-optimization
  annotations:
    description: "Service for the Optimization Engine component of the AI-driven Freight Optimization Platform"
    prometheus.io/scrape: "true"
    prometheus.io/port: "3003"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3003
      protocol: TCP
  selector:
    app: optimization-engine
  sessionAffinity: None