apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: market-intelligence-service
  namespace: default
  labels:
    app: market-intelligence-service
    component: market-intelligence
    part-of: freight-optimization
  annotations:
    description: "Horizontal Pod Autoscaler for the Market Intelligence Service that analyzes market conditions and adjusts pricing based on supply/demand dynamics"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: market-intelligence-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Pods
    pods:
      metric:
        name: rate_calculation_requests
      target:
        type: AverageValue
        averageValue: '100'
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 2
        periodSeconds: 60
      - type: Percent
        value: 50
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 120
      - type: Percent
        value: 10
        periodSeconds: 120
      selectPolicy: Min