apiVersion: v1
kind: Service
metadata:
  name: event-bus
  namespace: default
  labels:
    app: event-bus
    component: event-bus
    part-of: freight-optimization
  annotations:
    description: "Service for the Event Bus component of the AI-driven Freight Optimization Platform"
    prometheus.io/scrape: "true"
    prometheus.io/port: "3001"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3001
      protocol: TCP
  selector:
    app: event-bus
  sessionAffinity: None