apiVersion: v1
kind: Service
metadata:
  name: data-service
  namespace: default
  labels:
    app: data-service
    component: data-service
    part-of: freight-optimization
  annotations:
    description: "Service for the Data Service component that provides analytics, reporting, and data export operations"
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: data-service
  sessionAffinity: None