apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freight-platform-ingress
  namespace: default
  labels:
    app: freight-platform
    component: ingress
    part-of: freight-optimization
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_http_version 1.1;
spec:
  rules:
  - host: "{{ .Values.ingress.hosts[0].host }}"
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              name: http
      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              name: http
      - path: /ws/tracking
        pathType: Prefix
        backend:
          service:
            name: tracking-service
            port:
              name: websocket
      - path: /ws/notifications
        pathType: Prefix
        backend:
          service:
            name: notification-service
            port:
              name: websocket
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              name: http
  tls:
  - hosts:
    - "{{ .Values.ingress.hosts[0].host }}"
    secretName: freight-platform-tls