apiVersion: v1
kind: Service
metadata:
  name: load-service
  namespace: default
  labels:
    app: load-service
    component: backend
    part-of: freight-optimization
  annotations:
    description: "Service for the Load Service component that manages load lifecycle from creation to delivery, including status tracking and documentation"
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: load-service
  sessionAffinity: None