apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: false
    jsonData:
      timeInterval: 15s
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: logs-*
    isDefault: false
    version: 1
    editable: false
    jsonData:
      timeField: '@timestamp'
      esVersion: '7.10.0'
      maxConcurrentShardRequests: 5
      logMessageField: message
      logLevelField: level

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger-query:16686
    isDefault: false
    version: 1
    editable: false
    jsonData:
      nodeGraph:
        enabled: true

  - name: PostgreSQL
    type: postgres
    url: postgres-exporter:9187
    access: proxy
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    database: freight_platform
    isDefault: false
    version: 1
    editable: false
    jsonData:
      sslmode: disable
      postgresVersion: 1200
      timescaledb: false

  - name: TimescaleDB
    type: postgres
    url: timescaledb:5432
    access: proxy
    user: ${TIMESCALE_USER}
    secureJsonData:
      password: ${TIMESCALE_PASSWORD}
    database: metrics
    isDefault: false
    version: 1
    editable: false
    jsonData:
      sslmode: disable
      postgresVersion: 1200
      timescaledb: true

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis-exporter:9121
    isDefault: false
    version: 1
    editable: false
    jsonData:
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0

  - name: MongoDB
    type: mongodb-datasource
    access: proxy
    url: mongodb-exporter:9216
    isDefault: false
    version: 1
    editable: false
    jsonData:
      connection_string: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongodb:27017/admin

  - name: Kafka
    type: prometheus
    access: proxy
    url: http://kafka-exporter:9308
    isDefault: false
    version: 1
    editable: false
    jsonData:
      timeInterval: 15s
      httpMethod: GET