apiVersion: v1
kind: Service
metadata:
  name: gamification-service
  namespace: default
  labels:
    app: gamification-service
    component: gamification
    part-of: freight-optimization
  annotations:
    description: "Service for the Gamification Service component of the AI-driven Freight Optimization Platform"
    prometheus.io/scrape: "true"
    prometheus.io/port: "3004"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3004
      protocol: TCP
  selector:
    app: gamification-service
  sessionAffinity: None