apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: default
  labels:
    app: notification-service
    component: notification-service
    part-of: freight-optimization
  annotations:
    description: "Configuration for the Notification Service that delivers alerts, messages, and updates to users across multiple channels"
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  SERVICE_NAME: "notification-service"
  SERVICE_PORT: "3010"
  WEBSOCKET_PORT: "3011"
  WEBSOCKET_PATH: "/notifications"
  NOTIFICATION_WEBSOCKET_ENABLED: "true"
  NOTIFICATION_KAFKA_GROUP_ID: "notification-service-group"
  NOTIFICATION_TOPIC: "notifications"
  NOTIFICATION_EVENTS_TOPIC: "notification-events"
  KAFKA_TOPIC_SYSTEM_EVENTS: "system-events"
  KAFKA_TOPIC_NOTIFICATION_EVENTS: "notification-events"
  NOTIFICATION_DELIVERY_TIMEOUT: "30000"
  NOTIFICATION_RETRY_ATTEMPTS: "3"
  NOTIFICATION_RETRY_DELAY: "5000"
  NOTIFICATION_BATCH_SIZE: "100"
  NOTIFICATION_PROCESSING_INTERVAL: "5000"
  NOTIFICATION_CACHE_TTL: "86400"
  NOTIFICATION_QUEUE_JOB_RETENTION: "7"
  NOTIFICATION_QUEUE_CONCURRENCY: "5"
  MONGODB_URI: "mongodb://mongodb:27017/notification-service"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  KAFKA_BROKERS: "kafka:9092"
  EMAIL_SERVICE: "sendgrid"
  EMAIL_FROM_ADDRESS: "notifications@freight-optimization.com"
  EMAIL_FROM_NAME: "Freight Optimization Platform"
  SMS_SERVICE: "twilio"
  SMS_FROM_NUMBER: "+15551234567"
  PUSH_SERVICE: "firebase"
  ENABLE_EMAIL_NOTIFICATIONS: "true"
  ENABLE_SMS_NOTIFICATIONS: "true"
  ENABLE_PUSH_NOTIFICATIONS: "true"
  ENABLE_IN_APP_NOTIFICATIONS: "true"
  CORS_ORIGIN: "*"
  CORS_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_ALLOWED_HEADERS: "Content-Type,Authorization"
  RATE_LIMIT_MAX: "100"
  RATE_LIMIT_WINDOW_MS: "60000"
  NOTIFICATION_TEMPLATES_PATH: "/app/templates"
  NOTIFICATION_HISTORY_RETENTION_DAYS: "90"
  HEALTH_CHECK_PATH: "/health"
  METRICS_PATH: "/metrics"
  ENABLE_SWAGGER: "false"