apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: default
  labels:
    app: api-gateway
    component: api-gateway
    part-of: freight-optimization
  annotations:
    description: "Configuration for the API Gateway service of the AI-driven Freight Optimization Platform"
data:
  # CORS Configuration
  CORS_ORIGIN: "*"
  
  # Rate Limiting Configuration
  RATE_LIMIT_MAX: "1000"
  RATE_LIMIT_WINDOW_MS: "900000"
  
  # Logging Configuration
  LOG_LEVEL: "info"
  
  # Redis Configuration
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  
  # Service URLs for routing
  AUTH_SERVICE_URL: "http://auth-service:3000"
  DRIVER_SERVICE_URL: "http://driver-service:3000"
  LOAD_SERVICE_URL: "http://load-service:3000"
  LOAD_MATCHING_SERVICE_URL: "http://load-matching-service:3000"
  TRACKING_SERVICE_URL: "http://tracking-service:3000"
  GAMIFICATION_SERVICE_URL: "http://gamification-service:3000"
  MARKET_INTELLIGENCE_SERVICE_URL: "http://market-intelligence-service:3000"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3000"
  OPTIMIZATION_ENGINE_URL: "http://optimization-engine:3000"
  INTEGRATION_SERVICE_URL: "http://integration-service:3000"
  CACHE_SERVICE_URL: "http://cache-service:3000"
  DATA_SERVICE_URL: "http://data-service:3000"
  
  # Service Health and Circuit Breaker Configuration
  SERVICE_HEALTH_CHECK_INTERVAL_MS: "30000"
  SERVICE_TIMEOUT_MS: "10000"
  CIRCUIT_BREAKER_FAILURE_THRESHOLD: "50"
  CIRCUIT_BREAKER_RESET_TIMEOUT_MS: "30000"
  
  # API Gateway Configuration
  ENABLE_SWAGGER: "true"
  API_GATEWAY_BASE_PATH: "/api/v1"
  BODY_LIMIT: "1mb"
  
  # Differentiated Rate Limiting
  PUBLIC_RATE_LIMIT_MAX: "100"
  PUBLIC_RATE_LIMIT_WINDOW_MS: "900000"
  AUTHENTICATED_RATE_LIMIT_MAX: "1000"
  AUTHENTICATED_RATE_LIMIT_WINDOW_MS: "900000"