apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: load-matching-service
  namespace: default
  labels:
    app: load-matching-service
    component: load-matching
    part-of: freight-optimization
  annotations:
    description: 'Horizontal Pod Autoscaler for the Load Matching Service that matches drivers with loads based on AI predictions, driver preferences, and network optimization goals'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: load-matching-service
  minReplicas: 2
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Pods
    pods:
      metric:
        name: queue_depth
      target:
        type: AverageValue
        averageValue: '100'
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 2
        periodSeconds: 60
      - type: Percent
        value: 50
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 120
      - type: Percent
        value: 10
        periodSeconds: 120
      selectPolicy: Min