apiVersion: v1
kind: Service
metadata:
  name: load-matching-service
  namespace: default
  labels:
    app: load-matching-service
    component: load-matching
    part-of: freight-optimization
  annotations:
    description: "Service for the Load Matching Service component of the AI-driven Freight Optimization Platform"
    prometheus.io/scrape: "true"
    prometheus.io/port: "3004"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3004
      protocol: TCP
  selector:
    app: load-matching-service
  sessionAffinity: None