apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: driver-service
  namespace: default
  labels:
    app: driver-service
    component: backend
    part-of: freight-optimization
  annotations:
    description: "Horizontal Pod Autoscaler for the Driver Service that manages driver profiles, preferences, availability, and HOS compliance"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: driver-service
  minReplicas: 3
  maxReplicas: 12
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Pods
    pods:
      metric:
        name: active_sessions
      target:
        type: AverageValue
        averageValue: '100'
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 2
        periodSeconds: 60
      - type: Percent
        value: 50
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 120
      - type: Percent
        value: 10
        periodSeconds: 120
      selectPolicy: Min