apiVersion: v1
kind: Service
metadata:
  name: driver-service
  namespace: default
  labels:
    app: driver-service
    component: backend
    part-of: freight-optimization
  annotations:
    description: "Service for the Driver Service component that manages driver profiles, preferences, availability, and HOS compliance"
    prometheus.io/scrape: "true"
    prometheus.io/port: "3002"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3002
      protocol: TCP
  selector:
    app: driver-service
  sessionAffinity: None