# This workflow handles CI for the Driver Mobile Application
# It performs linting, testing, and building for both Android and iOS platforms

name: Driver App CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/web/driver-app/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/web/driver-app/**'

env:
  NODE_VERSION: '18.x'
  JAVA_VERSION: '11'
  RUBY_VERSION: '3.0'
  WORKING_DIRECTORY: src/web/driver-app

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: '${{ env.WORKING_DIRECTORY }}/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: npm run lint
    
    - name: TypeScript type checking
      run: npm run typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: '${{ env.WORKING_DIRECTORY }}/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test -- --coverage --ci --reporters=default --reporters=jest-junit
      env:
        JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ${{ env.WORKING_DIRECTORY }}/reports/junit/
        retention-days: 14
        
    - name: Upload test coverage
      uses: actions/upload-artifact@v3
      with:
        name: test-coverage
        path: ${{ env.WORKING_DIRECTORY }}/coverage
        retention-days: 14

  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: [lint, test]
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: '${{ env.WORKING_DIRECTORY }}/package-lock.json'
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ env.JAVA_VERSION }}
        cache: gradle
    
    - name: Install dependencies
      run: npm ci
    
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Create .env file
      run: echo "${{ secrets.REACT_NATIVE_ENV_VARS }}" > .env
    
    - name: Setup Android keystore
      env:
        ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      run: |
        # Skip if keystore isn't provided (e.g., for PR builds)
        if [ -n "$ANDROID_KEYSTORE_BASE64" ]; then
          echo $ANDROID_KEYSTORE_BASE64 | base64 --decode > android/app/my-release-key.keystore
          echo "KEYSTORE_PASSWORD=$ANDROID_KEYSTORE_PASSWORD" >> android/gradle.properties
          echo "KEY_ALIAS=$ANDROID_KEY_ALIAS" >> android/gradle.properties
          echo "KEY_PASSWORD=$ANDROID_KEY_PASSWORD" >> android/gradle.properties
        fi
    
    - name: Build Android Release
      run: |
        cd android
        ./gradlew bundleRelease assembleRelease
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: ${{ env.WORKING_DIRECTORY }}/android/app/build/outputs/apk/release/*.apk
        retention-days: 14
        
    - name: Upload AAB
      uses: actions/upload-artifact@v3
      with:
        name: android-aab
        path: ${{ env.WORKING_DIRECTORY }}/android/app/build/outputs/bundle/release/*.aab
        retention-days: 14

  build-ios:
    name: Build iOS
    runs-on: macos-latest
    needs: [lint, test]
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: '${{ env.WORKING_DIRECTORY }}/package-lock.json'
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
    
    - name: Cache CocoaPods
      uses: actions/cache@v3
      with:
        path: ${{ env.WORKING_DIRECTORY }}/ios/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install CocoaPods
      run: |
        cd ios
        pod install
    
    - name: Create .env file
      run: echo "${{ secrets.REACT_NATIVE_ENV_VARS }}" > .env
    
    - name: Build iOS App
      run: |
        cd ios
        xcodebuild -workspace DriverApp.xcworkspace -scheme DriverApp -configuration Release -sdk iphonesimulator -derivedDataPath build CODE_SIGNING_ALLOWED=NO
    
    - name: Upload iOS App
      uses: actions/upload-artifact@v3
      with:
        name: ios-app
        path: ${{ env.WORKING_DIRECTORY }}/ios/build/Build/Products/Release-iphonesimulator/*.app
        retention-days: 14